### ISSUE TITLE
Errro when starting

### ISSUE THREAD

**Issue by AviJonas08** [Xvirus0/Xvirus-Tools#13]
C:\Users\Jonas\Xvirus-Tools>xvirus.py
Traceback (most recent call last):
  File "C:\Users\Jonas\Xvirus-Tools\Xvirus.py", line 1, in <module>
    from util.plugins.common import *
  File "C:\Users\Jonas\Xvirus-Tools\util\plugins\common.py", line 15, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

**Comment by AviJonas08** [comment]
Windows 11

**Comment by DXVVAY** [comment]
Hmmm I'll take a look at it when I'm home
