### ISSUE TITLE
error when launching

### ISSUE THREAD

**Issue by cocorico8** [Xvirus0/Xvirus-Tools#16]
C:\Users\coco\Desktop\Xvirus-Tools>python Xvirus.py
Traceback (most recent call last):
  File "C:\Users\coco\Desktop\Xvirus-Tools\Xvirus.py", line 1, in <module>
    from util.plugins.common import *
  File "C:\Users\coco\Desktop\Xvirus-Tools\util\plugins\common.py", line 15, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

**Comment by DXVVAY** [comment]
Install keyboard by opening a terminal and typing pip install keyboard

**Comment by cocorico8** [comment]
now i have this 

C:\Users\coco\Desktop\Xvirus-Tools>python Xvirus.py
Traceback (most recent call last):
  File "C:\Users\coco\Desktop\Xvirus-Tools\Xvirus.py", line 1, in <module>
    from util.plugins.common import *
  File "C:\Users\coco\Desktop\Xvirus-Tools\util\plugins\common.py", line 630, in <module>
    Welcome {username}!"""
NameError: name 'username' is not defined

**Comment by DXVVAY** [comment]
It will be fixed in yhe next updat
